name: Run Python Script and Commit Changes

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 2 minutes
  workflow_dispatch:  # Allows you to trigger the workflow manually

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the Python script
        run: python jobsearch.py

      - name: Check for changes and commit
        run: |
          # Check if there are any changes in the repository
          if [ -n "$(git status --porcelain)" ]; then
            # Set up Git configuration for the commit
            git config --global user.name "Vishva Luke"
            git config --global user.email "vishvaluke@gmail.com"
            
            # Add the file and commit changes
            git add last_posting_id.txt
            git commit -m "Update last_posting_id.txt with latest details"
            git push
          else
            echo "No changes to commit."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
