name: Run Python Script and Commit Changes

on:
  schedule:
    #- cron: '0 */5 * * *'  # Runs every 5 hours
    - cron: '*/2 * * * *'  # Runs every 5 hours


jobs:
  run-python-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the Python script
        run: python jobsearch.py

      - name: Check for changes and commit
        run: |
          # Check if there are any changes in the repository
          git diff --exit-code || echo "Changes detected"

          # If there are changes, commit them
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.name "Vishva Luke"
            git config --global user.email "vishvaluke@gmail.com"
            git add your_file.txt
            git commit -m "Update your_file.txt with latest details"
            git push
          else
            echo "No changes to commit."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}